add_subdirectory(
    ${CMAKE_CURRENT_SOURCE_DIR}/../../../kernel
    ${CMAKE_CURRENT_BINARY_DIR}/kernel
)

add_executable(maxrtos_kernel_test_process test_process.c)
target_link_libraries(maxrtos_kernel_test_process PRIVATE maxrtos_kernel)
add_test(NAME kernel_process_tests COMMAND maxrtos_kernel_test_process)

add_executable(maxrtos_kernel_test_scheduler test_scheduler.c)
target_link_libraries(maxrtos_kernel_test_scheduler PRIVATE maxrtos_kernel)
add_test(NAME kernel_scheduler_tests COMMAND maxrtos_kernel_test_scheduler)

add_executable(maxrtos_kernel_test_frame test_frame.c)
target_link_libraries(maxrtos_kernel_test_frame PRIVATE maxrtos_kernel)
add_test(NAME kernel_frame_tests COMMAND maxrtos_kernel_test_frame)

add_executable(maxrtos_kernel_test_dispatch test_dispatch.c)
target_link_libraries(maxrtos_kernel_test_dispatch PRIVATE maxrtos_kernel)
add_test(NAME kernel_dispatch_tests COMMAND maxrtos_kernel_test_dispatch)

add_executable(maxrtos_kernel_test_partition test_partition.c)
target_link_libraries(maxrtos_kernel_test_partition PRIVATE maxrtos_kernel)
add_test(NAME kernel_partition_tests COMMAND maxrtos_kernel_test_partition)

add_executable(maxrtos_kernel_test_health_monitor test_health_monitor.c)
target_link_libraries(maxrtos_kernel_test_health_monitor PRIVATE maxrtos_kernel)
add_test(NAME kernel_health_monitor_tests COMMAND maxrtos_kernel_test_health_monitor)

add_executable(maxrtos_kernel_test_queue_port test_queue_port.c)
target_link_libraries(maxrtos_kernel_test_queue_port PRIVATE maxrtos_kernel)
add_test(NAME kernel_queue_port_tests COMMAND maxrtos_kernel_test_queue_port)

add_executable(maxrtos_kernel_test_fault_recovery test_fault_recovery.c)
target_link_libraries(maxrtos_kernel_test_fault_recovery PRIVATE maxrtos_kernel)
add_test(NAME kernel_fault_recovery_tests COMMAND maxrtos_kernel_test_fault_recovery)

add_executable(maxrtos_kernel_test_tick test_tick.c)
target_link_libraries(maxrtos_kernel_test_tick PRIVATE maxrtos_kernel)
add_test(NAME kernel_tick_tests COMMAND maxrtos_kernel_test_tick)

add_executable(maxrtos_kernel_test_yield test_yield.c)
target_link_libraries(maxrtos_kernel_test_yield PRIVATE maxrtos_kernel)
add_test(NAME kernel_yield_tests COMMAND maxrtos_kernel_test_yield)

add_executable(maxrtos_kernel_test_start_scheduler test_start_scheduler.c)
target_link_libraries(maxrtos_kernel_test_start_scheduler PRIVATE maxrtos_kernel)
add_test(NAME kernel_start_scheduler_tests COMMAND maxrtos_kernel_test_start_scheduler)

add_executable(maxrtos_kernel_test_waitlist test_waitlist.c)
target_link_libraries(maxrtos_kernel_test_waitlist PRIVATE maxrtos_kernel)
add_test(NAME kernel_start_waitlist_tests COMMAND maxrtos_kernel_test_waitlist)

add_executable(maxrtos_kernel_test_timing test_timing.c)
target_link_libraries(maxrtos_kernel_test_timing PRIVATE maxrtos_kernel)
add_test(NAME kernel_timing_tests COMMAND maxrtos_kernel_test_timing)
