/**
 * AUTO-GENERATED by maxrtos_codegen -- DO NOT EDIT BY HAND.
 * Source: tools/maxrtos_codegen/examples/example_module_with_ports.json
 *
 * Application-facing RTOS configuration interface: partition identifiers,
 * process stacks and priorities. MPU, partition-table, and frame-schedule
 * configuration is implemented in maxrtos_config.c. Processes are created by
 * the application; maxrtos_scheduler_start() (maxrtos/scheduler.h) starts them.
 *
 * Board initialization (clocks, GPIO, and SysTick timing) is the application's
 * responsibility. Call board_init() before maxrtos_config_init().
 */

#ifndef EXAMPLE_MODULE_RTOS_CONFIG_H
#define EXAMPLE_MODULE_RTOS_CONFIG_H

#include <stdint.h>

#include "maxrtos/kernel/process.h"
#include "maxrtos/kernel/partition.h"
#include "maxrtos/kernel/frame.h"
#include "maxrtos/arch/cortex_m7/systick.h" /* declares maxrtos_arch_systick(), called from your SysTick_Handler */

#ifdef __cplusplus
extern "C" {
#endif

/* Partition identifiers. */
#define PARTITION_ID_control ( ( maxrtos_partition_id_t ) 0U )
#define PARTITION_ID_application ( ( maxrtos_partition_id_t ) 1U )
/* Partition MPU domain sizes: one MPU region per partition covers all of its process stacks. */
#define PARTITION_DOMAIN_SIZE_control ( 2048U )
#define PARTITION_DOMAIN_SIZE_application ( 512U )

/* Process stacks (defined and placed by maxrtos_config.c / linker), each inside its partition's domain. */
extern uint8_t maxrtos_stack_control_main[ 512 ];
#define PROCESS_STACK_SIZE_control_main ( 512U )
#define PROCESS_PRIORITY_control_main ( 5U )
extern uint8_t maxrtos_stack_control_log[ 1024 ];
#define PROCESS_STACK_SIZE_control_log ( 1024U )
#define PROCESS_PRIORITY_control_log ( 7U )
extern uint8_t maxrtos_stack_application_main[ 512 ];
#define PROCESS_STACK_SIZE_application_main ( 512U )
#define PROCESS_PRIORITY_application_main ( 5U )
/**
 * Static IPC port buffers (defined and placed by maxrtos_config.c / linker).
 *
 * The generated configuration initializes each queue/sampling port once in
 * maxrtos_config_init(), before any process is allowed to send or receive.
 * Application code only needs the raw shared-memory storage and the queue
 * sizing constants used by that generated initialization.
 */
extern uint8_t maxrtos_port_cmd_channel[ 1024 ];
#define PORT_SIZE_cmd_channel ( 1024U )
#define PORT_MESSAGE_SIZE_cmd_channel ( 4U )
#define PORT_CAPACITY_cmd_channel ( 4U )

/**
 * Runs all one-time RTOS initialization: partition table, MPU configuration,
 * hardware initialization, context-switch initialization, and frame
 * scheduler initialization.
 *
 * Call once after board_init() and before creating any processes. After
 * creating them with maxrtos_process_create(), call maxrtos_scheduler_start().
 *
 * Configuration errors halt execution because they indicate invalid static
 * configuration rather than recoverable runtime conditions.
 */
void maxrtos_config_init( void );

#ifdef __cplusplus
}
#endif

#endif /* EXAMPLE_MODULE_RTOS_CONFIG_H */