/**
 * AUTO-GENERATED by maxrtos_codegen -- DO NOT EDIT BY HAND.
 * Source: tools/maxrtos_codegen/examples/example_module_with_ports.json
 *
 * Generated MPU configuration, partition-table wiring, and frame-schedule
 *
 * This file contains the generated RTOS configuration details. Application
 * code should include maxrtos_config.h and call maxrtos_config_init(), create
 * its processes, then call maxrtos_scheduler_start().
 */

#include "maxrtos_config.h"

#include <stdbool.h>

#include "maxrtos/arch/cortex_m7/context_switch.h"
#include "maxrtos/arch/cortex_m7/systick.h"
#include "maxrtos/arch/cortex_m7/mpu.h"
#include "maxrtos/arch/cortex_m7/mpu_hw.h"
#include "maxrtos/arch/cortex_m7/fault_handlers.h"
#include "maxrtos/kernel/health_monitor.h"
#include "maxrtos/kernel/queue_port.h"

#define MAXRTOS_CONFIG_HALT() \
    do { for( ;; ) { __asm volatile ( "bkpt #0" ); } } while( 0 )

#define MAXRTOS_CONFIG_CHECK( expr_ ) \
    do { if( ( expr_ ) != MAXRTOS_OK ) { MAXRTOS_CONFIG_HALT(); } } while( 0 )

/* Partition MPU domain bases, provided by the generated linker script. */
extern uint8_t __partition_control_domain_start[];
extern uint8_t __partition_application_domain_start[];

/* Process stacks, placed inside their partition's domain by the linker script. */
uint8_t maxrtos_stack_control_main[ 512 ]
    __attribute__((
        aligned( 512 ),
        section( ".partition_control_control_main_stack" )
    ));
uint8_t maxrtos_stack_control_log[ 1024 ]
    __attribute__((
        aligned( 1024 ),
        section( ".partition_control_control_log_stack" )
    ));
uint8_t maxrtos_stack_application_main[ 512 ]
    __attribute__((
        aligned( 512 ),
        section( ".partition_application_application_main_stack" )
    ));
/* Static IPC port buffers, placed by the generated linker script. */
uint8_t maxrtos_port_cmd_channel[ 1024 ]
    __attribute__((
        aligned( 1024 ),
        section( ".port_cmd_channel" )
    ));
static maxrtos_partition_table_t s_partition_table;
static maxrtos_frame_schedule_t s_frame_schedule;
static maxrtos_mpu_config_t s_mpu_config;
static maxrtos_health_monitor_t s_health_monitor;
static bool s_ipc_ports_initialized = false;

void maxrtos_config_init( void )
{
    maxrtos_process_pool_init();
    MAXRTOS_CONFIG_CHECK( maxrtos_partition_table_init( &s_partition_table ) );
    maxrtos_arch_set_partition_table( &s_partition_table );

    /* Health monitor: per-partition recovery policy for each fault class,
     * then enable the fault exceptions that report into it. Without this an
     * MPU violation escalates to HardFault and is never classified. */
    MAXRTOS_CONFIG_CHECK( maxrtos_hm_init( &s_health_monitor ) );
    MAXRTOS_CONFIG_CHECK( maxrtos_hm_set_policy(
        &s_health_monitor,
        PARTITION_ID_control,
        MAXRTOS_FAULT_MEMORY_ACCESS,
        MAXRTOS_HM_ACTION_RESTART_PROCESS ) );
    MAXRTOS_CONFIG_CHECK( maxrtos_hm_set_policy(
        &s_health_monitor,
        PARTITION_ID_control,
        MAXRTOS_FAULT_BUS_ERROR,
        MAXRTOS_HM_ACTION_RESTART_PROCESS ) );
    MAXRTOS_CONFIG_CHECK( maxrtos_hm_set_policy(
        &s_health_monitor,
        PARTITION_ID_control,
        MAXRTOS_FAULT_ILLEGAL_INSTRUCTION,
        MAXRTOS_HM_ACTION_RESTART_PROCESS ) );
    MAXRTOS_CONFIG_CHECK( maxrtos_hm_set_policy(
        &s_health_monitor,
        PARTITION_ID_control,
        MAXRTOS_FAULT_DIVIDE_BY_ZERO,
        MAXRTOS_HM_ACTION_RESTART_PROCESS ) );
    MAXRTOS_CONFIG_CHECK( maxrtos_hm_set_policy(
        &s_health_monitor,
        PARTITION_ID_control,
        MAXRTOS_FAULT_DEADLINE_EXCEEDED,
        MAXRTOS_HM_ACTION_RESTART_PROCESS ) );
    MAXRTOS_CONFIG_CHECK( maxrtos_hm_set_policy(
        &s_health_monitor,
        PARTITION_ID_application,
        MAXRTOS_FAULT_MEMORY_ACCESS,
        MAXRTOS_HM_ACTION_RESTART_PROCESS ) );
    MAXRTOS_CONFIG_CHECK( maxrtos_hm_set_policy(
        &s_health_monitor,
        PARTITION_ID_application,
        MAXRTOS_FAULT_BUS_ERROR,
        MAXRTOS_HM_ACTION_RESTART_PROCESS ) );
    MAXRTOS_CONFIG_CHECK( maxrtos_hm_set_policy(
        &s_health_monitor,
        PARTITION_ID_application,
        MAXRTOS_FAULT_ILLEGAL_INSTRUCTION,
        MAXRTOS_HM_ACTION_RESTART_PROCESS ) );
    MAXRTOS_CONFIG_CHECK( maxrtos_hm_set_policy(
        &s_health_monitor,
        PARTITION_ID_application,
        MAXRTOS_FAULT_DIVIDE_BY_ZERO,
        MAXRTOS_HM_ACTION_RESTART_PROCESS ) );
    MAXRTOS_CONFIG_CHECK( maxrtos_hm_set_policy(
        &s_health_monitor,
        PARTITION_ID_application,
        MAXRTOS_FAULT_DEADLINE_EXCEEDED,
        MAXRTOS_HM_ACTION_RESTART_PROCESS ) );
    maxrtos_arch_set_health_monitor( &s_health_monitor );
    maxrtos_arch_fault_handlers_init();


    /* MPU configuration. */
    MAXRTOS_CONFIG_CHECK( maxrtos_mpu_config_init( &s_mpu_config ) );

    MAXRTOS_CONFIG_CHECK( maxrtos_mpu_set_partition_region(
        &s_mpu_config,
        PARTITION_ID_control,
        ( uint32_t ) __partition_control_domain_start,
        2048U,
        MAXRTOS_MPU_ACCESS_READ_WRITE,
        false ) );
    MAXRTOS_CONFIG_CHECK( maxrtos_mpu_set_partition_region(
        &s_mpu_config,
        PARTITION_ID_application,
        ( uint32_t ) __partition_application_domain_start,
        512U,
        MAXRTOS_MPU_ACCESS_READ_WRITE,
        false ) );
    maxrtos_arch_mpu_set_config( &s_mpu_config );

    maxrtos_arch_mpu_configure_region(
        0U,
        0x08000000UL,
        2097152U,
        MAXRTOS_MPU_ACCESS_READ_ONLY,
        true );
    maxrtos_arch_mpu_configure_region(
        1U,
        0x58000000UL,
        524288U,
        MAXRTOS_MPU_ACCESS_READ_WRITE,
        false );
    maxrtos_arch_mpu_configure_region(
        2U,
        0x20000000UL,
        131072U,
        MAXRTOS_MPU_ACCESS_PRIV_READ_WRITE,
        false );
    maxrtos_arch_mpu_configure_region(
        3U,
        0x24000000UL,
        524288U,
        MAXRTOS_MPU_ACCESS_PRIV_READ_WRITE,
        false );
    /* Static IPC port regions. */
    MAXRTOS_CONFIG_CHECK( maxrtos_mpu_add_port_region(
        &s_mpu_config,
        ( uint32_t ) maxrtos_port_cmd_channel,
        1024U,
        (1UL << 0U) | (1UL << 1U) ) );
    if( !s_ipc_ports_initialized )
    {
        _Static_assert(
            sizeof( maxrtos_queue_port_t ) <= 1024U,
            "cmd_channel port too small for maxrtos_queue_port_t" );

        MAXRTOS_CONFIG_CHECK( maxrtos_queue_port_init(
            ( maxrtos_queue_port_t * ) maxrtos_port_cmd_channel,
            4U,
            4U ) );
        s_ipc_ports_initialized = true;
    }
    maxrtos_arch_mpu_init( false );

    {
        static maxrtos_frame_slot_t s_frame_slots[ 2 ];
        s_frame_slots[ 0 ].partition_id = 0U;
        s_frame_slots[ 0 ].duration_ticks = 5U;
        s_frame_slots[ 1 ].partition_id = 1U;
        s_frame_slots[ 1 ].duration_ticks = 3U;
        MAXRTOS_CONFIG_CHECK( maxrtos_frame_init(
            &s_frame_schedule, s_frame_slots, 2U ) );
    }

    /* Initialize context switching and the frame-scheduled SysTick. */
    maxrtos_arch_context_switch_init();
    maxrtos_arch_systick_init( &s_frame_schedule, &s_partition_table );
}