/**
 * AUTO-GENERATED by maxrtos_codegen -- DO NOT EDIT BY HAND.
 * Source: examples/example_module_with_ports.json
 *
 * Everything the application needs to create its processes and start the
 * scheduler. All MPU / partition-table / frame-schedule wiring lives in
 * maxrtos_config.c and is intentionally not exposed here.
 *
 * Board bring-up (clocks, GPIO, and SysTick timing) is NOT this tool's
 * concern -- provide it yourself via board.h / board.c and call
 * board_init() before maxrtos_config_init().
 */
#ifndef EXAMPLE_MODULE_RTOS_CONFIG_H
#define EXAMPLE_MODULE_RTOS_CONFIG_H

#include <stdint.h>
#include "maxrtos/kernel/process.h"
#include "maxrtos/kernel/partition.h"
#include "maxrtos/kernel/frame.h"
#include "maxrtos/arch/cortex_m7/systick.h" /* declares maxrtos_arch_systick(), called from your SysTick_Handler */

#ifdef __cplusplus
extern "C" {
#endif

/* --- Partition identifiers ------------------------------------------- */
#define PARTITION_ID_control ( ( maxrtos_partition_id_t ) 0U )
#define PARTITION_ID_application ( ( maxrtos_partition_id_t ) 1U )
/* --- Partition stacks (defined + placed by maxrtos_config.c / linker) --- */
extern uint8_t maxrtos_stack_control[ 512 ];
#define PARTITION_STACK_SIZE_control ( 512U )
extern uint8_t maxrtos_stack_application[ 512 ];
#define PARTITION_STACK_SIZE_application ( 512U )
/**
 * --- Static IPC port buffers (defined + placed by maxrtos_config.c / linker) ---
 *
 * Each buffer below is raw, MPU-protected shared memory -- readable and
 * writable only by the partitions declared as members in the config, and
 * unreachable by every other partition. This generator does not know the
 * internal layout of maxrtos_queue_port_t / maxrtos_sampling_port_t, so
 * it does not construct one for you: cast the buffer and call
 * maxrtos_queue_port_init() / maxrtos_sampling_port_init() yourself,
 * once, from a partition that is a declared member, sized so that
 * sizeof(maxrtos_queue_port_t) (or _sampling_port_t) does not exceed
 * PORT_SIZE_<name>.
 */
extern uint8_t maxrtos_port_cmd_channel[ 128 ];
#define PORT_SIZE_cmd_channel ( 128U )

/**
 * Runs all one-time RTOS setup: partition table, MPU region table +
 * hardware init, context-switch init, and systick-driven frame scheduler
 * init. Call once, after board_init(), before creating any processes.
 * Halts (bkpt) on internal failure -- these are configuration-time
 * invariants, not runtime conditions the application should recover from.
 */
void maxrtos_config_init( void );

/**
 * Registers the given process IDs with their partitions (per this
 * config's partition assignment) and starts the major-frame scheduler.
 * Call once, after creating one process per partition with
 * maxrtos_process_create(). Does not return.
 */
void maxrtos_config_start(maxrtos_process_id_t id_control, maxrtos_process_id_t id_application);

#ifdef __cplusplus
}
#endif

#endif /* EXAMPLE_MODULE_RTOS_CONFIG_H */